#!/bin/bash

name="Sam"
day=$(date +%A)
count=5
files=(report1.txt report2.txt report3.txt)
pid=$$

echo "Hi $name, today is $day."
echo "There are $count files to process."
echo "The files are: ${files[*]}"
echo "The first file is: ${files[0]}"
echo "Script is running with PID: $pid"
echo "2 + 3 = $((2 + 3))"
echo "Length of your name is ${#name} characters."
echo "Default value test (unset var): ${not_set:-default_value}"
echo "This won't expand: '\$name'"

last_cmd_status=$?
echo "Exit status of last command: $last_cmd_status"
